services:
  nextcloud_db:
    image: postgres:13-bookworm
    hostname: nextcloud_db
    container_name: nextcloud_db
    restart: always
    volumes:               
     - ./database:/var/lib/postgresql/data                   
    env_file: .env   
    networks:            
      - nextcloud_db      

  nextcloud_redis:
    container_name: nextcloud_redis
    hostname: nextcloud_redis
    image: redis:7.4
    restart: always
    networks:
      - nextcloud_db

  nextcloud_app:  
    image: nextcloud:30
    restart: always
    ports:
      - 8090:80
    depends_on:
      - nextcloud_db
    volumes:
      - ./data/www/html:/var/www/html
    networks:
      - nextcloud_db
      - frontend

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.rule=Host(`nuage.$DOMAIN`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      - "traefik.http.routers.nextcloud.middlewares=nextcloud_custom_header, nextcloud_redirectregex"

      - "traefik.http.middlewares.nextcloud_custom_header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud_custom_header.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains"
      - "traefik.http.middlewares.nextcloud_custom_header.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN}"

      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"

  onlyoffice:
    container_name: onlyoffice
    hostname: onlyoffice
    depends_on:
      - nextcloud_app
    image: onlyoffice/documentserver:8.2
    restart: always
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.onlyoffice.tls.certresolver=myresolver"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.$DOMAIN`)"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice_custom_header"
      - "traefik.http.middlewares.onlyoffice_custom_header.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}"
      - "traefik.http.middlewares.onlyoffice_custom_header.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains"
      - "traefik.http.middlewares.onlyoffice_custom_header.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN}"

networks:
  frontend:
    external: true
  nextcloud_db:
    internal: true




