services:
  nextcloud_db:
    image: postgres:13-bookworm
    hostname: nextcloud_db
    container_name: nextcloud_db
    restart: always
    volumes:               
     - ./database:/var/lib/postgresql/data                   
    env_file: .env   
    networks:            
      - nextcloud_db      

  nextcloud_redis:
    container_name: nextcloud_redis
    hostname: nextcloud_redis
    image: redis:7.4
    restart: always
    networks:
      - nextcloud_db

  nextcloud_app:  
    container_name: nextcloud_app
    hostname: nextcloud_app
    image: nextcloud:30
    restart: always
    ports:
      - 8090:80
    depends_on:
      - nextcloud_db
    volumes:
      - ./data/www/html:/var/www/html
    networks:
      - nextcloud_db
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.rule=Host(`nuage.$DOMAIN`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      - "traefik.http.routers.nextcloud.middlewares=nextcloud_custom_header, nextcloud_redirectregex"

      - "traefik.http.middlewares.nextcloud_custom_header.headers.customFrameOptionsValue=ALLOW-FROM http://${DOMAIN} https://${DOMAIN} ${DOMAIN} http://onlyoffice.${DOMAIN} https://onlyoffice.${DOMAIN}"
      - "traefik.http.middlewares.nextcloud_custom_header.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload;"
      - "traefik.http.middlewares.nextcloud_custom_header.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN} onlyoffice.${DOMAIN} "

      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"

      # - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW
      # - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN}
      # - traefik.http.middlewares.nextcloud.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN
      # - traefik.http.middlewares.nextcloud.headers.accesscontrolalloworigin=*

    # extra_hosts:
    #   - ${DOMAIN}:172.18.0.1
    #   - nuage.${DOMAIN}:172.18.0.1
    #   - onlyoffice.${DOMAIN}:172.18.0.1
    #   - auth.${DOMAIN}:172.18.0.1

  onlyoffice:
    container_name: onlyoffice
    hostname: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    networks:
      - frontend
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ENABLE_SSL: true
    expose:
      - '80'
      - '443'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.onlyoffice.tls.certresolver=myresolver"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.$DOMAIN`)"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-https-redirect"
      - "traefik.http.middlewares.onlyoffice-https-redirect.redirectscheme.scheme=https"

      # - "traefik.http.routers.onlyoffice.middlewares=onlyoffice_custom_header"
      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.contentSecurityPolicy=default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://onlyoffice.lamiete.fr; frame-ancestors 'self' https://${DOMAIN} onlyoffice.${DOMAIN} *.${DOMAIN};"
      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}"
      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains;  preload;"

      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}"
      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload;" #https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#an_example_scenario
      # - "traefik.http.middlewares.onlyoffice_custom_header.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN} *.${DOMAIN} nuage.${DOMAIN}"

  # #     ## Extra headers for onlyoffice
  # #     - traefik.http.routers.onlyoffice.tls=true
  # #     - traefik.http.middlewares.cors-headers.headers.accessControlAllowOrigin=*
  #     # - traefik.http.middlewares.onlyoffice.headers.customRequestHeaders.X-Forwarded-Proto=https
  #     # - traefik.http.middlewares.onlyoffice.headers.accesscontrolalloworigin=*
    
    # extra_hosts:
    #   - ${DOMAIN}:172.18.0.1
    #   - nuage.${DOMAIN}:172.18.0.1
    #   - onlyoffice.${DOMAIN}:172.18.0.1
    #   - auth.${DOMAIN}:172.18.0.1


networks:
  frontend:
    external: true
  nextcloud_db:
    internal: true



# allow to set onlyoffice as local conainer
# command: sudo -u www-data sh -c "php occ --no-warnings config:system:set allow_local_remote_servers --value=true"

# Exemple pour reconstruire les index après une maj :
# docker compose exec --user www-data nextcloud_app php occ db:add-missing-indices

# Scanner les fichier sur disque dur et reconstruire la base de donnée ( utilse en cas de suppression de fichier depuis le terminal ) 
# docker compose exec --user www-data nextcloud_app php occ files:scan jonas
# docker compose exec --user www-data nextcloud_app php occ files:scan --path="Ekopratik/files/Ekopratik/2. Administration/2.2 Salariat/2.2.1 En cours/"
# docker compose exec --user www-data nextcloud_app php occ trashbin:cleanup Ekopratik

# docker compose exec --user www-data nextcloud_app php occ maintenance:mode --on
